### ISSUE TITLE
Request for update to Arduino json 7

### ISSUE THREAD

**Issue by wltue** [iddi/oocsi-esp#11]
https://arduinojson.org/v7/how-to/upgrade-from-v6/

**Comment by matsfunk** [comment]
Hi,

Sorry for the delay. Thanks for opening an issue, I have finally updated the library for ArduinoJson v7. This includes code changes to benefit from the library developments. I hope this saves everyone some trouble over the next months. @wltue @edenchiang 

Cheers,
Mathias

**Comment by wltue** [comment]
Thank you. Will update wthin couple of weeks.
