### ISSUE TITLE
If you failed to compile oocsi for ESP8266 ...

### ISSUE THREAD

**Issue by sarkrui** [iddi/oocsi-esp#3]
For those who are using OOCSI on ESP8266, no matter which specific board, don't update esp8266 core to 3.0.x. IDE won't compile and give the below error. Core v2.7.4 would work just great.

```
error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
```

@matsfunk Perhaps it's great to indicate the tested/compatible core versions in the README.

**Comment by matsfunk** [comment]
Perhaps it's better to fix it right away. :)
This issue is fixed in commit 4e54892cff33d2be607af097fdfd0c7a79b2c547 and we have released [Version 1.5.7](https://github.com/iddi/oocsi-esp/releases/tag/v1.5.7) just now.
